
[Worldgen]
	enable_emerald_bee_nest = true
	enable_lapis_bee_nest = true
	enable_quartz_bee_nest = true
	enable_ender_bee_nest = true
	enable_diamond_bee_nest = true
	enable_iron_bee_nest = true
	enable_gold_bee_nest = true
	enable_redstone_bee_nest = true

